version: '2.1'

services:
  stalk-fcm-admin-interface:
    image: stalk-fcm-admin-interface
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 9001:9001
      - 9229:9229
    ## set your startup file here
    command: node --inspect index.js